name: CI
on: [push, pull_request]
jobs:
build_test:
runs-on: ubuntu-latest
services:
postgres:
image: postgres:16-alpine
env:
POSTGRES_USER: app
POSTGRES_PASSWORD: app
POSTGRES_DB: tickets
ports: ["5432:5432"]
options: >-
--health-cmd "pg_isready -U app" --health-interval 5s --health-timeout 3s --health-retries 20
redis:
image: redis:7-alpine
ports: ["6379:6379"]
steps:
- uses: actions/checkout@v4
- uses: pnpm/action-setup@v4
with: { version: 9 }
- uses: actions/setup-node@v4
with:
node-version: 20
cache: 'pnpm'
- run: pnpm install --frozen-lockfile
- run: pnpm -C apps/api prisma migrate deploy
env:
DATABASE_URL: postgresql://app:app@localhost:5432/tickets
- run: pnpm -C apps/api test -- --ci
- run: pnpm -C apps/web build